# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd extendedglob
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/kyran/.zshrc'
autoload -Uz compinit
compinit
# End of lines added by compinstall

function chpwd() {
	print -Pn "\e]2;%~\a"
	ls --color --group-directories-first -ap
}

# function to add Vim modeline
RPS1=""
function zle-line-init zle-keymap-select zle-line-finish {

	if [ $KEYMAP = vicmd ]; then
		# the command mode for vi
		echo -ne "\e[2 q"
	else
		# the insert mode for vi
		echo -ne "\e[6 q"
	fi
    VIM_PROMPT="%F{250}%K{234} [%  NORMAL ]%  %k%f %{$reset_color%}"
    INS_PROMPT="%F{250}%K{234} [%  INSERT ]%  %k%f %{$reset_color%}"
    VIS_PROMPT="%F{250}%K{234} [%  VISUAL ]%  %k%f %{$reset_color%}"
    RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/$INS_PROMPT}"
    zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

# Aliases #
alias update="pacaur -Syu --noconfirm --noedit"
alias ll="ls --color --group-directories-first -aohp"
alias la="ls --color --group-directories-first -ap"
alias clr="clear"

export KEYTIMEOUT=2
bindkey kj vi-cmd-mode
bindkey jk vi-cmd-mode
bindkey -M visual 'kj' deactivate-region
bindkey -M visual 'jk' deactivate-region

#bindkey "<BS>" backward-delete-char
#bindkey "<Del>" delete-char

bindkey -M vicmd '^z' undo
bindkey -M vicmd '^r' redo

bindkey -M vicmd 'n' vi-insert
bindkey -M vicmd 'N' vi-insert-bol
bindkey -M vicmd 'm' vi-add-next
bindkey -M vicmd 'M' vi-add-eol

bindkey -M vicmd 'f' vi-change
bindkey -M vicmd 's' visual-mode
bindkey -M vicmd 'S' visual-line-mode

bindkey -M vicmd 'c' vi-yank
bindkey -M vicmd 'v' vi-put-after

bindkey -M vicmd 'j' vi-backward-char
bindkey -M viopp 'j' vi-backward-char
bindkey -M visual 'j' vi-backward-char
bindkey -M vicmd ';' vi-forward-char
bindkey -M viopp ';' vi-forward-char
bindkey -M visual ';' vi-forward-char
bindkey -M vicmd 'k' vi-up-line-or-history
bindkey -M viopp 'k' vi-up-line-or-history
bindkey -M vicmd 'l' vi-down-line-or-history
bindkey -M viopp 'l' vi-down-line-or-history

bindkey -M vicmd 'gj' vi-beginning-of-line
bindkey -M viopp 'gj' vi-beginning-of-line
bindkey -M visual 'gj' vi-beginning-of-line
bindkey -M vicmd 'g;' vi-end-of-line
bindkey -M viopp 'g;' vi-end-of-line
bindkey -M visual 'g;' vi-end-of-line

bindkey -M vicmd 'p' vi-forward-word
bindkey -M viopp 'p' vi-forward-word
bindkey -M visual 'p' vi-forward-word
bindkey -M vicmd 'P' vi-forward-blank-word
bindkey -M viopp 'P' vi-forward-blank-word
bindkey -M visual 'P' vi-forward-blank-word

bindkey -M vicmd 'o' vi-forward-word-end
bindkey -M viopp 'o' vi-forward-word-end
bindkey -M visual 'o' vi-forward-word-end
bindkey -M vicmd 'O' vi-forward-blank-word-end
bindkey -M viopp 'O' vi-forward-blank-word-end
bindkey -M visual 'O' vi-forward-blank-word-end

bindkey -M vicmd 'i' vi-backward-word
bindkey -M viopp 'i' vi-backward-word
bindkey -M visual 'i' vi-backward-word
bindkey -M vicmd 'I' vi-backward-blank-word
bindkey -M viopp 'I' vi-backward-blank-word
bindkey -M visual 'I' vi-backward-blank-word
 
bindkey -M vicmd 'u' vi-backward-word-end
bindkey -M viopp 'u' vi-backward-word-end
bindkey -M visual 'u' vi-backward-word-end
bindkey -M vicmd 'U' vi-backward-blank-word-end
bindkey -M viopp 'U' vi-backward-blank-word-end
bindkey -M visual 'U' vi-backward-blank-word-end

bindkey -M viopp 'sw' select-in-word
bindkey -M viopp 'sW' select-in-blank-word
bindkey -M visual 'sw' select-in-word
bindkey -M visual 'sW' select-in-blank-word
 
NEWLINE=$'\n'
PS1="${NEWLINE}%F{246}%n:%m%f %F{250}%K{234} %~ %k%f ${NEWLINE} %F{130}➤%f  "
export VISUAL=/usr/bin/nvim
export EDITOR="$VISUAL"
export RANGER_LOAD_DEFAULT_RC=FALSE
export VIM_TERM_COMPAT=1

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
